# fly.toml app configuration file generated for datingapp3 on 2023-12-12T21:02:55+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp3"
primary_region = "sin"

[build]
  image = "mskipd/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "363562677546997"
  CloudinarySettings__CloudName = "dmoieoksq"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
